stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: eduardotartas/gerenciamento-rural-api:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker buildx create --use
    - docker buildx build --platform linux/arm64 -t $DOCKER_IMAGE --push .

deploy_job:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - k3s-runner
  script:
    - kubectl set image deployment/gerenciamento-rural-api gerenciamento-rural-api=$DOCKER_IMAGE -n pasto-livre
    - kubectl rollout status deployment/gerenciamento-rural-api -n pasto-livre
  only:
    - main
